// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGNbMC1aHV-dZQfrORfinSFEh99G2y-aM',
    appId: '1:1025806225881:web:70df3d30b85c7ff50a09c8',
    messagingSenderId: '1025806225881',
    projectId: 'householdexpenses-5e1f9',
    authDomain: 'householdexpenses-5e1f9.firebaseapp.com',
    storageBucket: 'householdexpenses-5e1f9.appspot.com',
    measurementId: 'G-WS54RDY1N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQPERL899w0-Ek1qLBNoSvglk71xfCqzU',
    appId: '1:1025806225881:android:00213ef75e7800c10a09c8',
    messagingSenderId: '1025806225881',
    projectId: 'householdexpenses-5e1f9',
    storageBucket: 'householdexpenses-5e1f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAONwvVFWZH54YRShzzg7fEzzAeBRq0cY',
    appId: '1:1025806225881:ios:36ded232a9fcd42b0a09c8',
    messagingSenderId: '1025806225881',
    projectId: 'householdexpenses-5e1f9',
    storageBucket: 'householdexpenses-5e1f9.appspot.com',
    iosClientId: '1025806225881-hkonndeeqn9ud598s08m5knb12gn0e2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.householdExpensesAppFlutter',
  );
}
